// Built-in check catalog. Every entry is a declarative Rule (see DESIGN.md §3.2);
// custom rules authored in the UI use the exact same shape and are evaluated by
// the same engine. Seeded from the reference Falcon Shield report.

import type { Rule } from "../types";

export const BUILTIN_RULES: Rule[] = [
  // ───────────────────────────── Malware Protection ─────────────────────────────
  {
    id: "malware.clickjack_setup", domain: "Malware Protection", severity: "High",
    title: "Clickjack Protection for Setup Pages",
    description: "Clickjack protection for setup pages prevents them being framed by external sites.",
    info: "Setup pages contain sensitive administrative functions. If embedded in a malicious frame, attackers could trick admins into unintended configuration changes.",
    remediation: "Setup > Session Settings > Clickjack Protection: keep 'Enable clickjack protection for Setup pages' on.",
    check: { source: "healthcheck", kind: "setting", path: "malware.clickjackSetup", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.7", "A.8.26"], NIST_800_53: ["SC-23"], SOC2: ["CC6.8"], CSA_CCM: ["TVM-02"] },
  },
  {
    id: "malware.clickjack_nonsetup", domain: "Malware Protection", severity: "High",
    title: "Clickjack Protection for Non-Setup Pages",
    description: "Clickjack protection for non-setup pages is enabled.",
    info: "Clickjacking tricks users into interacting with hidden elements, leading to unauthorized data modification or privilege escalation.",
    remediation: "Setup > Session Settings > Clickjack Protection: keep non-Setup page protection on.",
    check: { source: "healthcheck", kind: "setting", path: "malware.clickjackNonSetup", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.7", "A.8.26"], NIST_800_53: ["SC-23"], SOC2: ["CC6.8"], CSA_CCM: ["TVM-02"] },
  },
  {
    id: "malware.clickjack_vf_std", domain: "Malware Protection", severity: "High",
    title: "Clickjack Protection for Customer Visualforce (standard headers)",
    description: "Clickjack protection for customer VF pages with standard headers is enabled.",
    info: "Prevents VF pages with standard headers from being framed by unauthorized external sites.",
    remediation: "Setup > Session Settings: enable clickjack protection for customer VF pages with standard headers.",
    check: { source: "metadata", kind: "setting", path: "malware.clickjackVfStandard", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.26"], NIST_800_53: ["SC-23"], SOC2: ["CC6.8"] },
  },
  {
    id: "malware.clickjack_vf_nohdr", domain: "Malware Protection", severity: "High",
    title: "Clickjack Protection for Customer Visualforce (disabled headers)",
    description: "Clickjack protection for customer VF pages with disabled headers is enabled.",
    info: "Covers VF pages where showHeader=false, which otherwise lose the standard framing protection.",
    remediation: "Setup > Session Settings: enable clickjack protection for customer VF pages with disabled headers.",
    check: { source: "metadata", kind: "setting", path: "malware.clickjackVfDisabledHeaders", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.26"], NIST_800_53: ["SC-23"], SOC2: ["CC6.8"] },
  },
  {
    id: "malware.csrf_get", domain: "Malware Protection", severity: "High",
    title: "CSRF Protection (GET requests, non-setup pages)",
    description: "CSRF protection on GET requests for non-setup pages is enabled.",
    info: "CSRF exploits the trust an app has in an authenticated user's browser to perform unauthorized actions.",
    remediation: "Setup > Session Settings > CSRF Protection: keep GET-request protection enabled.",
    check: { source: "healthcheck", kind: "setting", path: "malware.csrfGet", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.26"], NIST_800_53: ["AC-6(1)"], SOC2: ["CC6.8"] },
  },
  {
    id: "malware.csrf_post", domain: "Malware Protection", severity: "High",
    title: "CSRF Protection (POST requests, non-setup pages)",
    description: "CSRF protection on POST requests for non-setup pages is enabled.",
    info: "Blocks forged state-changing requests submitted on behalf of an authenticated user.",
    remediation: "Setup > Session Settings > CSRF Protection: keep POST-request protection enabled.",
    check: { source: "healthcheck", kind: "setting", path: "malware.csrfPost", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.26"], NIST_800_53: ["AC-6(1)"], SOC2: ["CC6.8"] },
  },
  {
    id: "malware.coep", domain: "Malware Protection", severity: "High",
    title: "Cross-Origin Embedder Policy (COEP)",
    description: "COEP is enforced for Visualforce/Experience pages.",
    info: "COEP prevents a document from loading cross-origin resources that don't explicitly grant permission, mitigating side-channel and data-leak attacks.",
    remediation: "Enable Cross-Origin Embedder Policy in Session Settings / Experience Builder security.",
    check: { source: "metadata", kind: "setting", path: "malware.coep", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.26"], SOC2: ["CC6.8"] },
  },
  {
    id: "malware.coop", domain: "Malware Protection", severity: "High",
    title: "Cross-Origin Opener Policy (COOP)",
    description: "COOP is enforced for Visualforce/Experience pages.",
    info: "COOP isolates the browsing context group, preventing cross-origin windows from referencing each other.",
    remediation: "Enable Cross-Origin Opener Policy in Session Settings / Experience Builder security.",
    check: { source: "metadata", kind: "setting", path: "malware.coop", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.26"], SOC2: ["CC6.8"] },
  },
  {
    id: "malware.content_sniffing", domain: "Malware Protection", severity: "Medium",
    title: "Content Sniffing Protection",
    description: "MIME content-sniffing protection is enabled.",
    info: "Prevents browsers from reinterpreting uploaded files as executable content types.",
    remediation: "Enable content sniffing protection in File Upload and Download Security settings.",
    check: { source: "metadata", kind: "setting", path: "malware.contentSniffing", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.7"], NIST_800_53: ["SI-10"] },
  },
  {
    id: "malware.html_upload", domain: "Malware Protection", severity: "Medium",
    title: "HTML File Upload Blocked",
    description: "Upload/execution of HTML files in the browser is blocked.",
    info: "HTML uploads can carry stored XSS payloads that execute in a victim's authenticated session.",
    remediation: "File Upload and Download Security: set HTML behavior to 'Download' (do not execute in browser).",
    check: { source: "metadata", kind: "setting", path: "malware.htmlUploadBlocked", op: "==", value: true },
    compliance: { NIST_800_53: ["SI-10(5)"], CSA_CCM: ["TVM-02"] },
  },

  // ───────────────────────────── Access Control ─────────────────────────────
  {
    id: "access.invalid_login_attempts", domain: "Access Control", severity: "High",
    title: "Maximum Invalid Login Attempts Set",
    description: "A finite lockout threshold is configured (not 'No Limit').",
    info: "Without a lockout limit, accounts are exposed to unlimited brute-force and credential-stuffing attempts.",
    remediation: "Setup > Password Policies: set Maximum Invalid Login Attempts to a finite value (e.g. 10).",
    check: { source: "healthcheck", kind: "setting", path: "access.maxInvalidLoginAttempts", op: ">", value: 0 },
    compliance: { ISO_27001_2022: ["A.8.5"], NIST_800_53: ["AC-7"], PCI_DSS_4: ["8.3.4"] },
  },
  {
    id: "access.remote_site_https", domain: "Access Control", severity: "High",
    title: "Remote Sites Use HTTPS",
    description: "All Remote Site Settings enforce protocol security (HTTPS).",
    info: "Callouts over HTTP expose data and credentials to interception and tampering in transit.",
    remediation: "Setup > Remote Site Settings: ensure 'Disable Protocol Security' is unchecked for every remote site.",
    check: { source: "metadata", kind: "setting", path: "access.remoteSitesAllHttps", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.21", "A.8.24"], NIST_800_53: ["SC-8(3)"] },
  },
  {
    id: "access.sso_enabled", domain: "Access Control", severity: "High",
    title: "Single Sign-On (SAML/OIDC) Enabled",
    description: "Federated SSO is configured and active.",
    info: "SSO centralizes authentication and MFA enforcement and removes standalone local passwords as an attack vector.",
    remediation: "Configure SAML/OIDC SSO and enforce it via My Domain login policy.",
    check: { source: "metadata", kind: "setting", path: "access.ssoEnabled", op: "==", value: true },
    compliance: { NIST_800_53: ["IA-2(10)"], SOC2: ["CC6.1"] },
  },
  {
    id: "access.enforce_custom_domain", domain: "Access Control", severity: "High",
    title: "Enforce Authentication Through My Domain",
    description: "Login through login.salesforce.com is prevented; My Domain is enforced.",
    info: "Enforcing My Domain ensures SSO/session policies apply and blocks generic-endpoint logins that bypass them.",
    remediation: "Setup > My Domain > Authentication Configuration: prevent login from login.salesforce.com.",
    check: { source: "metadata", kind: "setting", path: "access.enforceCustomDomain", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.5"], NIST_800_53: ["IA-2(10)"] },
  },
  {
    id: "access.force_logout_timeout", domain: "Access Control", severity: "Medium",
    title: "Force Logout on Session Timeout",
    description: "Sessions are terminated (not just locked) at timeout.",
    info: "Force logout invalidates the session so an idle session cannot be resumed from a shared device.",
    remediation: "Setup > Session Settings: enable 'Force logout on session timeout'.",
    check: { source: "healthcheck", kind: "setting", path: "access.forceLogoutOnTimeout", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.5.18"], NIST_800_53: ["AC-12"] },
  },
  {
    id: "access.ip_every_request", domain: "Access Control", severity: "Medium",
    title: "Enforce Login IP Ranges on Every Request",
    description: "Login IP ranges are enforced on every page request, not only at login.",
    info: "Per-request enforcement prevents a session established from a trusted IP being continued from an untrusted one.",
    remediation: "Setup > Session Settings: enable 'Enforce login IP ranges on every request'.",
    check: { source: "healthcheck", kind: "setting", path: "access.ipEveryRequest", op: "==", value: true },
    compliance: { NIST_800_53: ["SC-7(5)"] },
  },
  {
    id: "access.warn_redirect", domain: "Access Control", severity: "Medium",
    title: "Warn on Redirect Out of Salesforce",
    description: "Users are warned before being redirected to an external domain.",
    info: "Redirect warnings reduce the success of phishing links that bounce users to malicious sites.",
    remediation: "Setup > Session Settings: enable redirection warnings for external links.",
    check: { source: "metadata", kind: "setting", path: "access.warnRedirect", op: "==", value: true },
    compliance: { NIST_800_53: ["AC-3(3)"] },
  },
  {
    id: "access.require_mydomain_api", domain: "Access Control", severity: "Medium",
    title: "Require My Domain for API Logins",
    description: "API logins must use the org's My Domain host.",
    info: "Requiring My Domain for API logins ensures policy enforcement and consistent hostnames for integrations.",
    remediation: "Setup > My Domain: require My Domain hostnames for all API logins.",
    check: { source: "metadata", kind: "setting", path: "access.requireMyDomainForApi", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.5"], NIST_800_53: ["IA-2(10)"] },
  },

  // ───────────────────────────── Password Management ─────────────────────────────
  {
    id: "pwd.expiration_org", domain: "Password Management", severity: "High",
    title: "Password Expiration Policy (org)",
    description: "Org password expiration follows modern guidance (no forced periodic rotation).",
    info: "NIST SP 800-63B recommends against forced periodic password expiration; rotate only on evidence of compromise.",
    remediation: "Setup > Password Policies: set 'User passwords expire in' to 'Never expires' and rely on MFA + breach monitoring.",
    check: { source: "healthcheck", kind: "setting", path: "pwd.expirationDays", op: "==", value: 0 },
    compliance: { NIST_800_53: ["IA-5(1)"], ISO_27001_2022: ["A.8.5"] },
  },
  {
    id: "pwd.min_lifetime", domain: "Password Management", severity: "Medium",
    title: "Minimum One-Day Password Lifetime",
    description: "A minimum password lifetime is enforced.",
    info: "Prevents users from cycling through the password history to return to a favored password immediately.",
    remediation: "Setup > Password Policies: enforce a minimum 1-day password lifetime.",
    check: { source: "healthcheck", kind: "setting", path: "pwd.minLifetime", op: "==", value: true },
    compliance: { NIST_800_53: ["IA-5(1)"] },
  },
  {
    id: "pwd.min_length", domain: "Password Management", severity: "Medium",
    title: "Minimum Password Length ≥ 8",
    description: "Minimum password length is at least 8 characters.",
    info: "Longer minimums materially increase resistance to brute-force and guessing attacks.",
    remediation: "Setup > Password Policies: set minimum password length to 8 or greater.",
    check: { source: "healthcheck", kind: "setting", path: "pwd.minLength", op: ">=", value: 8 },
    compliance: { NIST_800_53: ["IA-5(1)"], PCI_DSS_4: ["8.3.6"] },
  },
  {
    id: "pwd.history", domain: "Password Management", severity: "Medium",
    title: "Enforce Password History",
    description: "Password history is enforced (≥ 1 remembered password).",
    info: "Prevents immediate reuse of a previous password on reset.",
    remediation: "Setup > Password Policies: set 'Enforce password history' to remember at least 1 password.",
    check: { source: "healthcheck", kind: "setting", path: "pwd.history", op: ">=", value: 1 },
    compliance: { NIST_800_53: ["IA-5(1)"] },
  },

  // ───────────────────────────── Permissions ─────────────────────────────
  {
    id: "perm.view_all_data", domain: "Permissions", severity: "High",
    title: "Users with View All Data",
    description: "Number of active users with 'View All Data' is within policy.",
    info: "View All Data bypasses all sharing rules; it should be tightly limited to a small set of admins.",
    remediation: "Review View All Data holders and remove the permission where not business-critical.",
    check: { source: "soql", kind: "count", metric: "ViewAllData", op: "<=", threshold: 15 },
    compliance: { ISO_27001_2022: ["A.8.2", "A.8.3"], NIST_800_53: ["AC-6(7)"], SOC2: ["CC6.1"], PCI_DSS_4: ["7.2.4"] },
    tags: ["over-permissioning"],
  },
  {
    id: "perm.modify_all_data", domain: "Permissions", severity: "High",
    title: "Users with Modify All Data",
    description: "Number of active users with 'Modify All Data' is within policy.",
    info: "Modify All Data grants full create/edit/delete on all records regardless of sharing — the highest-impact data permission.",
    remediation: "Restrict Modify All Data to a minimal admin group; use targeted permission sets instead.",
    check: { source: "soql", kind: "count", metric: "ModifyAllData", op: "<=", threshold: 15 },
    compliance: { ISO_27001_2022: ["A.8.2", "A.8.3"], NIST_800_53: ["AC-6(7)"], SOC2: ["CC6.1"], PCI_DSS_4: ["7.2.4"] },
    tags: ["over-permissioning"],
  },
  {
    id: "perm.manage_users", domain: "Permissions", severity: "Medium",
    title: "Users with Manage Users",
    description: "Number of active users with 'Manage Users' is within policy.",
    info: "Manage Users can reset passwords, change profiles, and escalate privileges of other users.",
    remediation: "Limit Manage Users to identity/admin staff and review quarterly.",
    check: { source: "soql", kind: "count", metric: "ManageUsers", op: "<=", threshold: 17 },
    compliance: { NIST_800_53: ["AC-6(7)"], SOC2: ["CC6.1"] },
    tags: ["over-permissioning"],
  },
  {
    id: "perm.bulk_hard_delete", domain: "Permissions", severity: "Medium",
    title: "Users with Bulk API Hard Delete",
    description: "Number of active users with 'Bulk API Hard Delete' is within policy.",
    info: "Hard delete bypasses the Recycle Bin, permanently destroying records with no recovery.",
    remediation: "Remove Bulk API Hard Delete from all but a small set of controlled integration users.",
    check: { source: "soql", kind: "count", metric: "BulkApiHardDelete", op: "<=", threshold: 15 },
    compliance: { NIST_800_53: ["AC-6(7)"], ISO_27001_2022: ["A.8.3"] },
    tags: ["over-permissioning"],
  },
  {
    id: "perm.weekly_export", domain: "Permissions", severity: "Medium",
    title: "Users with Weekly Data Export",
    description: "Number of active users who can run the Weekly Data Export is within policy.",
    info: "Full data-export capability is a bulk-exfiltration risk if abused or compromised.",
    remediation: "Restrict 'Weekly Data Export' to backup/admin roles.",
    check: { source: "soql", kind: "count", metric: "WeeklyDataExport", op: "<=", threshold: 15 },
    compliance: { NIST_800_53: ["AC-6(7)"], ISO_27001_2022: ["A.8.12"] },
    tags: ["over-permissioning", "data-exfiltration"],
  },
  {
    id: "perm.delete_accounts", domain: "Permissions", severity: "Medium",
    title: "Users Who Can Delete Accounts",
    description: "Number of users with delete access on Account is within policy.",
    info: "Broad delete rights on core objects increase the blast radius of a compromised or careless user.",
    remediation: "Remove Account delete from profiles/permission sets that do not require it.",
    check: { source: "soql", kind: "count", metric: "DeleteAccounts", op: "<=", threshold: 5 },
    compliance: { NIST_800_53: ["AC-6(7)"], SOC2: ["CC6.1"] },
    tags: ["over-permissioning"],
  },

  // ───────────────────────────── MFA ─────────────────────────────
  {
    id: "mfa.all_direct_ui", domain: "MFA", severity: "Medium",
    title: "Require MFA for All Direct UI Logins",
    description: "MFA is required for all direct (non-SSO) UI logins.",
    info: "Direct UI logins without MFA are the most common account-takeover vector.",
    remediation: "Setup > Identity > MFA: require MFA for all direct UI logins (or enforce via permission set).",
    check: { source: "metadata", kind: "setting", path: "mfa.allDirectUiLogins", op: "==", value: true },
    compliance: { NIST_800_53: ["IA-2(1)"], PCI_DSS_4: ["8.4.2"], SOC2: ["CC6.1"] },
  },
  {
    id: "mfa.verify_registration", domain: "MFA", severity: "Medium",
    title: "Identity Verification During MFA Registration",
    description: "Identity is verified when users register MFA methods.",
    info: "Verifying identity at registration prevents an attacker binding their own MFA device to a victim account.",
    remediation: "Enable identity verification during MFA/device registration in Session Settings.",
    check: { source: "metadata", kind: "setting", path: "mfa.verifyOnRegistration", op: "==", value: true },
    compliance: { NIST_800_53: ["IA-2"], ISO_27001_2022: ["A.8.5"] },
  },

  // ───────────────────────────── Data Leakage Protection ─────────────────────────────
  {
    id: "dlp.owd_public", domain: "Data Leakage Protection", severity: "High",
    title: "Objects With Default External Access = Public",
    description: "No object has an org-wide default external access of Public.",
    info: "Public external OWD exposes records to guest/community users regardless of intent.",
    remediation: "Setup > Sharing Settings: set external OWD to Private for the flagged objects and grant access explicitly.",
    check: { source: "metadata", kind: "listEmpty", list: "objectsPublicExternal" },
    compliance: { ISO_27001_2022: ["A.8.12"], NIST_800_53: ["AC-21"] },
    tags: ["data-exposure"],
  },
  {
    id: "dlp.dashboard_snapshots", domain: "Data Leakage Protection", severity: "High",
    title: "Dashboard Component Snapshots Disabled",
    description: "Posting dashboard component snapshots to feeds is disabled.",
    info: "Snapshots can surface data to users who lack access to the underlying report.",
    remediation: "Setup > Report and Dashboard Settings: disable dashboard component snapshots.",
    check: { source: "metadata", kind: "setting", path: "dlp.dashboardSnapshots", op: "==", value: false },
    compliance: { ISO_27001_2022: ["A.8.12"], NIST_800_53: ["AC-21"] },
    tags: ["data-exposure"],
  },
  {
    id: "dlp.public_links_nopwd", domain: "Data Leakage Protection", severity: "High",
    title: "Public Links / Content Deliveries Without Password",
    description: "No active public link or content delivery lacks password protection.",
    info: "Password-less public deliveries expose files to anyone with the URL.",
    remediation: "Add passwords/expirations to the flagged content deliveries, or revoke them.",
    check: { source: "soql", kind: "listEmpty", list: "publicLinksNoPassword" },
    compliance: { ISO_27001_2022: ["A.8.12"], NIST_800_53: ["AC-6(6)"] },
    tags: ["data-exposure"],
  },

  // ───────────────────────────── Secure Baseline ─────────────────────────────
  {
    id: "baseline.pim_enhanced", domain: "Secure Baseline", severity: "High",
    title: "Enhanced Personal Information Management",
    description: "Enhanced PIM restricts which personal fields are visible to other internal users.",
    info: "Without enhanced PIM, users can see colleagues' personal contact fields by default.",
    remediation: "Setup > User Management Settings: enable Enhanced Personal Information Management.",
    check: { source: "metadata", kind: "setting", path: "baseline.pimEnhanced", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.5.34"], NIST_CSF_2: ["PR.AA-01"] },
  },
  {
    id: "baseline.guest_api_enabled", domain: "Secure Baseline", severity: "High",
    title: "Guest Profile Does Not Have API Enabled",
    description: "No guest/site profile has 'API Enabled'.",
    info: "API access on a guest profile lets unauthenticated visitors query data programmatically.",
    remediation: "Remove 'API Enabled' from all guest/site profiles.",
    check: { source: "metadata", kind: "setting", path: "baseline.guestApiEnabled", op: "==", value: false },
    compliance: { NIST_800_53: ["AC-6(10)"], ISO_27001_2022: ["A.8.2"] },
    tags: ["guest"],
  },
  {
    id: "baseline.profile_filtering", domain: "Secure Baseline", severity: "High",
    title: "Profile Filtering for Guest Users",
    description: "Profile filtering hides internal user records from guest users.",
    info: "Without profile filtering, guest users may enumerate internal user records.",
    remediation: "Setup > User Management Settings: enable profile filtering for guest users.",
    check: { source: "metadata", kind: "setting", path: "baseline.profileFiltering", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.9", "A.5.34"] },
    tags: ["guest"],
  },

  // ───────────────────────────── Auditing ─────────────────────────────
  {
    id: "audit.event_log_generation", domain: "Auditing", severity: "High",
    title: "Event Log Generation Enabled",
    description: "Event monitoring / event log file generation is enabled.",
    info: "Event logs are the primary source for detecting anomalous access and building an audit trail.",
    remediation: "Enable Event Monitoring and event log file generation.",
    check: { source: "metadata", kind: "setting", path: "audit.eventLogGeneration", op: "==", value: true },
    compliance: { NIST_800_53: ["AU-2", "AU-12"], SOC2: ["CC7.2"] },
  },
  {
    id: "audit.event_log_delete", domain: "Auditing", severity: "High",
    title: "Deletion of Event Monitoring Records Disabled",
    description: "Deletion of event monitoring records is disabled.",
    info: "Allowing deletion of audit records undermines the integrity of the audit trail.",
    remediation: "Disable deletion of event monitoring / big object audit records.",
    check: { source: "metadata", kind: "setting", path: "audit.eventLogDeleteDisabled", op: "==", value: true },
    compliance: { NIST_800_53: ["AU-9"], SOC2: ["CC7.2"] },
  },

  // ───────────────────────────── Privacy Control ─────────────────────────────
  {
    id: "privacy.view_pii", domain: "Privacy Control", severity: "Medium",
    title: "Users With Permission to View PII",
    description: "Number of users granted 'View Encrypted/PII Data' is within policy.",
    info: "PII visibility should be minimized to reduce exposure and support data-minimization requirements.",
    remediation: "Restrict PII-view permissions to roles with a documented need.",
    check: { source: "soql", kind: "count", metric: "ViewPII", op: "<=", threshold: 0 },
    compliance: { ISO_27001_2022: ["A.5.34"], NIST_800_53: ["AC-6(7)"] },
    tags: ["privacy"],
  },
];
