// Built-in check catalog. Every entry is a declarative Rule (see DESIGN.md §3.2);
// custom rules authored in the UI use the exact same shape and are evaluated by
// the same engine. Seeded from the reference Falcon Shield report.

import type { Rule } from "../types";

export const BUILTIN_RULES: Rule[] = [
  // ───────────────────────────── Malware Protection ─────────────────────────────
  {
    id: "malware.clickjack_setup", domain: "Malware Protection", severity: "High",
    title: "Clickjack Protection for Setup Pages",
    description: "Clickjack protection for setup pages prevents them being framed by external sites.",
    info: "Setup pages contain sensitive administrative functions. If embedded in a malicious frame, attackers could trick admins into unintended configuration changes.",
    remediation: "Setup > Session Settings > Clickjack Protection: keep 'Enable clickjack protection for Setup pages' on.",
    check: { source: "healthcheck", kind: "setting", path: "malware.clickjackSetup", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.7", "A.8.26"], NIST_800_53: ["SC-23"], SOC2: ["CC6.8"], CSA_CCM: ["TVM-02"] },
  },
  {
    id: "malware.clickjack_nonsetup", domain: "Malware Protection", severity: "High",
    title: "Clickjack Protection for Non-Setup Pages",
    description: "Clickjack protection for non-setup pages is enabled.",
    info: "Clickjacking tricks users into interacting with hidden elements, leading to unauthorized data modification or privilege escalation.",
    remediation: "Setup > Session Settings > Clickjack Protection: keep non-Setup page protection on.",
    check: { source: "healthcheck", kind: "setting", path: "malware.clickjackNonSetup", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.7", "A.8.26"], NIST_800_53: ["SC-23"], SOC2: ["CC6.8"], CSA_CCM: ["TVM-02"] },
  },
  {
    id: "malware.clickjack_vf_std", domain: "Malware Protection", severity: "High",
    title: "Clickjack Protection for Customer Visualforce (standard headers)",
    description: "Clickjack protection for customer VF pages with standard headers is enabled.",
    info: "Prevents VF pages with standard headers from being framed by unauthorized external sites.",
    remediation: "Setup > Session Settings: enable clickjack protection for customer VF pages with standard headers.",
    check: { source: "metadata", kind: "setting", path: "malware.clickjackVfStandard", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.26"], NIST_800_53: ["SC-23"], SOC2: ["CC6.8"] },
  },
  {
    id: "malware.clickjack_vf_nohdr", domain: "Malware Protection", severity: "High",
    title: "Clickjack Protection for Customer Visualforce (disabled headers)",
    description: "Clickjack protection for customer VF pages with disabled headers is enabled.",
    info: "Covers VF pages where showHeader=false, which otherwise lose the standard framing protection.",
    remediation: "Setup > Session Settings: enable clickjack protection for customer VF pages with disabled headers.",
    check: { source: "metadata", kind: "setting", path: "malware.clickjackVfDisabledHeaders", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.26"], NIST_800_53: ["SC-23"], SOC2: ["CC6.8"] },
  },
  {
    id: "malware.csrf_get", domain: "Malware Protection", severity: "High",
    title: "CSRF Protection (GET requests, non-setup pages)",
    description: "CSRF protection on GET requests for non-setup pages is enabled.",
    info: "CSRF exploits the trust an app has in an authenticated user's browser to perform unauthorized actions.",
    remediation: "Setup > Session Settings > CSRF Protection: keep GET-request protection enabled.",
    check: { source: "healthcheck", kind: "setting", path: "malware.csrfGet", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.26"], NIST_800_53: ["AC-6(1)"], SOC2: ["CC6.8"] },
  },
  {
    id: "malware.csrf_post", domain: "Malware Protection", severity: "High",
    title: "CSRF Protection (POST requests, non-setup pages)",
    description: "CSRF protection on POST requests for non-setup pages is enabled.",
    info: "Blocks forged state-changing requests submitted on behalf of an authenticated user.",
    remediation: "Setup > Session Settings > CSRF Protection: keep POST-request protection enabled.",
    check: { source: "healthcheck", kind: "setting", path: "malware.csrfPost", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.26"], NIST_800_53: ["AC-6(1)"], SOC2: ["CC6.8"] },
  },
  {
    id: "malware.coep", domain: "Malware Protection", severity: "High",
    title: "Cross-Origin Embedder Policy (COEP)",
    description: "COEP is enforced for Visualforce/Experience pages.",
    info: "COEP prevents a document from loading cross-origin resources that don't explicitly grant permission, mitigating side-channel and data-leak attacks.",
    remediation: "Enable Cross-Origin Embedder Policy in Session Settings / Experience Builder security.",
    check: { source: "metadata", kind: "setting", path: "malware.coep", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.26"], SOC2: ["CC6.8"] },
  },
  {
    id: "malware.coop", domain: "Malware Protection", severity: "High",
    title: "Cross-Origin Opener Policy (COOP)",
    description: "COOP is enforced for Visualforce/Experience pages.",
    info: "COOP isolates the browsing context group, preventing cross-origin windows from referencing each other.",
    remediation: "Enable Cross-Origin Opener Policy in Session Settings / Experience Builder security.",
    check: { source: "metadata", kind: "setting", path: "malware.coop", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.26"], SOC2: ["CC6.8"] },
  },
  {
    id: "malware.content_sniffing", domain: "Malware Protection", severity: "Medium",
    title: "Content Sniffing Protection",
    description: "MIME content-sniffing protection is enabled.",
    info: "Prevents browsers from reinterpreting uploaded files as executable content types.",
    remediation: "Enable content sniffing protection in File Upload and Download Security settings.",
    check: { source: "metadata", kind: "setting", path: "malware.contentSniffing", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.7"], NIST_800_53: ["SI-10"] },
  },
  {
    id: "malware.html_upload", domain: "Malware Protection", severity: "Medium",
    title: "HTML File Upload Blocked",
    description: "Upload/execution of HTML files in the browser is blocked.",
    info: "HTML uploads can carry stored XSS payloads that execute in a victim's authenticated session.",
    remediation: "File Upload and Download Security: set HTML behavior to 'Download' (do not execute in browser).",
    check: { source: "metadata", kind: "setting", path: "malware.htmlUploadBlocked", op: "==", value: true },
    compliance: { NIST_800_53: ["SI-10(5)"], CSA_CCM: ["TVM-02"] },
  },

  // ───────────────────────────── Access Control ─────────────────────────────
  {
    id: "access.invalid_login_attempts", domain: "Access Control", severity: "High",
    title: "Maximum Invalid Login Attempts Set",
    description: "A finite lockout threshold is configured (not 'No Limit').",
    info: "Without a lockout limit, accounts are exposed to unlimited brute-force and credential-stuffing attempts.",
    remediation: "Setup > Password Policies: set Maximum Invalid Login Attempts to a finite value (e.g. 10).",
    check: { source: "healthcheck", kind: "setting", path: "access.maxInvalidLoginAttempts", op: ">", value: 0 },
    compliance: { ISO_27001_2022: ["A.8.5"], NIST_800_53: ["AC-7"], PCI_DSS_4: ["8.3.4"] },
  },
  {
    id: "access.remote_site_https", domain: "Access Control", severity: "High",
    title: "Remote Sites Use HTTPS",
    description: "All Remote Site Settings enforce protocol security (HTTPS).",
    info: "Callouts over HTTP expose data and credentials to interception and tampering in transit.",
    remediation: "Setup > Remote Site Settings: ensure 'Disable Protocol Security' is unchecked for every remote site.",
    check: { source: "metadata", kind: "setting", path: "access.remoteSitesAllHttps", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.21", "A.8.24"], NIST_800_53: ["SC-8(3)"] },
  },
  {
    id: "access.sso_enabled", domain: "Access Control", severity: "High",
    title: "Single Sign-On (SAML/OIDC) Enabled",
    description: "Federated SSO is configured and active.",
    info: "SSO centralizes authentication and MFA enforcement and removes standalone local passwords as an attack vector.",
    remediation: "Configure SAML/OIDC SSO and enforce it via My Domain login policy.",
    check: { source: "metadata", kind: "setting", path: "access.ssoEnabled", op: "==", value: true },
    compliance: { NIST_800_53: ["IA-2(10)"], SOC2: ["CC6.1"] },
  },
  {
    id: "access.enforce_custom_domain", domain: "Access Control", severity: "High",
    title: "Enforce Authentication Through My Domain",
    description: "Login through login.salesforce.com is prevented; My Domain is enforced.",
    info: "Enforcing My Domain ensures SSO/session policies apply and blocks generic-endpoint logins that bypass them.",
    remediation: "Setup > My Domain > Authentication Configuration: prevent login from login.salesforce.com.",
    check: { source: "metadata", kind: "setting", path: "access.enforceCustomDomain", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.5"], NIST_800_53: ["IA-2(10)"] },
  },
  {
    id: "access.force_logout_timeout", domain: "Access Control", severity: "Medium",
    title: "Force Logout on Session Timeout",
    description: "Sessions are terminated (not just locked) at timeout.",
    info: "Force logout invalidates the session so an idle session cannot be resumed from a shared device.",
    remediation: "Setup > Session Settings: enable 'Force logout on session timeout'.",
    check: { source: "healthcheck", kind: "setting", path: "access.forceLogoutOnTimeout", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.5.18"], NIST_800_53: ["AC-12"] },
  },
  {
    id: "access.ip_every_request", domain: "Access Control", severity: "Medium",
    title: "Enforce Login IP Ranges on Every Request",
    description: "Login IP ranges are enforced on every page request, not only at login.",
    info: "Per-request enforcement prevents a session established from a trusted IP being continued from an untrusted one.",
    remediation: "Setup > Session Settings: enable 'Enforce login IP ranges on every request'.",
    check: { source: "healthcheck", kind: "setting", path: "access.ipEveryRequest", op: "==", value: true },
    compliance: { NIST_800_53: ["SC-7(5)"] },
  },
  {
    id: "access.warn_redirect", domain: "Access Control", severity: "Medium",
    title: "Warn on Redirect Out of Salesforce",
    description: "Users are warned before being redirected to an external domain.",
    info: "Redirect warnings reduce the success of phishing links that bounce users to malicious sites.",
    remediation: "Setup > Session Settings: enable redirection warnings for external links.",
    check: { source: "metadata", kind: "setting", path: "access.warnRedirect", op: "==", value: true },
    compliance: { NIST_800_53: ["AC-3(3)"] },
  },
  {
    id: "access.require_mydomain_api", domain: "Access Control", severity: "Medium",
    title: "Require My Domain for API Logins",
    description: "API logins must use the org's My Domain host.",
    info: "Requiring My Domain for API logins ensures policy enforcement and consistent hostnames for integrations.",
    remediation: "Setup > My Domain: require My Domain hostnames for all API logins.",
    check: { source: "metadata", kind: "setting", path: "access.requireMyDomainForApi", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.5"], NIST_800_53: ["IA-2(10)"] },
  },

  {
    id: "access.require_https", domain: "Access Control", severity: "High",
    title: "Require Secure Connections (HTTPS)",
    description: "The org requires HTTPS for all connections.",
    info: "Without enforced HTTPS, sessions and credentials can traverse plaintext HTTP and be intercepted or tampered with in transit.",
    remediation: "Setup > Session Settings: enable 'Require secure connections (HTTPS)'.",
    check: { source: "metadata", kind: "setting", path: "access.requireHttpsConnection", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.24"], NIST_800_53: ["SC-8", "SC-8(3)"], SOC2: ["CC6.7"], PCI_DSS_4: ["4.2.1"] },
  },
  {
    id: "access.disable_login_sf_credentials", domain: "Access Control", severity: "Medium",
    title: "Disable Login With Salesforce Credentials",
    description: "Local Salesforce credential login is disabled in favour of SSO.",
    info: "Leaving local credential login enabled lets users bypass the identity provider, sidestepping centrally enforced MFA and conditional access.",
    remediation: "Setup > Single Sign-On Settings: disable login with Salesforce credentials once SSO is verified.",
    check: { source: "metadata", kind: "setting", path: "access.disableLoginWithSfCredentials", op: "==", value: true },
    compliance: { NIST_800_53: ["IA-2(10)"], SOC2: ["CC6.1"], ISO_27001_2022: ["A.8.5"] },
  },
  {
    id: "access.require_http_only", domain: "Access Control", severity: "Medium",
    title: "Require HttpOnly Attribute",
    description: "Session cookies carry the HttpOnly attribute.",
    info: "HttpOnly prevents client-side scripts from reading the session cookie, blocking session theft through cross-site scripting.",
    remediation: "Setup > Session Settings: enable 'Require HttpOnly attribute'.",
    check: { source: "metadata", kind: "setting", path: "access.requireHttpOnly", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.26"], NIST_800_53: ["SC-23"], SOC2: ["CC6.8"] },
  },
  {
    id: "access.lock_sessions_domain", domain: "Access Control", severity: "Medium",
    title: "Lock Sessions to the Domain in Which They Were First Used",
    description: "A session cannot be reused from a different domain.",
    info: "Binding a session to its originating domain prevents a stolen session identifier being replayed against another hostname.",
    remediation: "Setup > Session Settings: enable 'Lock sessions to the domain in which they were first used'.",
    check: { source: "metadata", kind: "setting", path: "access.lockSessionsToDomain", op: "==", value: true },
    compliance: { NIST_800_53: ["SC-23"], ISO_27001_2022: ["A.8.26"] },
  },
  {
    id: "access.lock_sessions_ip", domain: "Access Control", severity: "Medium",
    title: "Lock Sessions to the Originating IP Address",
    description: "A session is tied to the IP address that created it.",
    info: "IP-bound sessions cannot be resumed from another network location, which defeats session hijacking from a different host.",
    remediation: "Setup > Session Settings: enable 'Lock sessions to the IP address from which they originated'.",
    check: { source: "metadata", kind: "setting", path: "access.lockSessionsToIp", op: "==", value: true },
    compliance: { NIST_800_53: ["SC-7(5)", "SC-23"], ISO_27001_2022: ["A.8.20"] },
  },
  {
    id: "access.relogin_after_login_as", domain: "Access Control", severity: "Medium",
    title: "Re-login After Login As User",
    description: "Admins must re-authenticate after ending a 'Login As' session.",
    info: "Without re-login, an administrator returning from an impersonated session can retain that elevated context, blurring the audit trail.",
    remediation: "Setup > Session Settings: enable 'Require re-login after Login-As-User'.",
    check: { source: "metadata", kind: "setting", path: "access.forceReloginAfterLoginAs", op: "==", value: true },
    compliance: { NIST_800_53: ["AC-6(9)", "AU-2"], SOC2: ["CC6.1"] },
  },
  {
    id: "access.terminate_sessions_pwd_reset", domain: "Access Control", severity: "Medium",
    title: "Enforce Session Termination On Admin Password Reset",
    description: "Existing sessions end when an admin resets a user's password.",
    info: "If sessions survive a password reset, an attacker who already holds a live session keeps access even after the credential is rotated.",
    remediation: "Setup > Session Settings: terminate user sessions when an admin resets the password.",
    check: { source: "metadata", kind: "setting", path: "access.terminateSessionsOnPasswordReset", op: "==", value: true },
    compliance: { NIST_800_53: ["AC-12", "IA-5"], ISO_27001_2022: ["A.8.5"] },
  },
  {
    id: "access.identity_confirm_email_change", domain: "Access Control", severity: "Low",
    title: "Require Identity Verification For Email Address Change",
    description: "Changing a user's email address requires identity verification.",
    info: "Unverified email changes let an attacker redirect password-reset messages to an address they control, enabling account takeover.",
    remediation: "Setup > Session Settings: require identity verification for email address changes.",
    check: { source: "metadata", kind: "setting", path: "access.identityConfirmOnEmailChange", op: "==", value: true },
    compliance: { NIST_800_53: ["IA-5"], ISO_27001_2022: ["A.8.5"] },
  },
  {
    id: "access.email_change_confirm_communities", domain: "Access Control", severity: "Low",
    title: "Email Confirmation For Email Change (External Users)",
    description: "External community users must confirm email address changes.",
    info: "External identities are frequently targeted; requiring confirmation stops silent redirection of account recovery mail.",
    remediation: "Setup > Session Settings: require email confirmation for changes made in Lightning communities.",
    check: { source: "metadata", kind: "setting", path: "access.emailChangeConfirmCommunities", op: "==", value: true },
    compliance: { NIST_800_53: ["IA-5"], ISO_27001_2022: ["A.8.5"] },
    tags: ["guest"],
  },
  {
    id: "access.certificate_auth", domain: "Access Control", severity: "Low",
    title: "Certificate-Based Authentication",
    description: "Mutual TLS certificate authentication is available for users.",
    info: "Certificate-based authentication binds access to a provisioned device credential that cannot be phished like a password.",
    remediation: "Setup > Session Settings: enable user authentication by certificate and distribute client certificates.",
    check: { source: "metadata", kind: "setting", path: "access.certificateBasedAuth", op: "==", value: true },
    compliance: { NIST_800_53: ["IA-2(1)", "IA-5(2)"], ISO_27001_2022: ["A.8.5"] },
  },
  {
    id: "access.no_autocomplete", domain: "Access Control", severity: "Low",
    title: "Disable Username Autocomplete on Login",
    description: "The login page does not cache or autocomplete usernames.",
    info: "Cached usernames on shared or kiosk devices disclose valid account names to the next person at the browser.",
    remediation: "Setup > Session Settings: disable 'Enable caching and autocomplete on login page'.",
    check: { source: "metadata", kind: "setting", path: "access.cacheAndAutocomplete", op: "==", value: false },
    compliance: { ISO_27001_2022: ["A.8.5"], NIST_800_53: ["AC-9"] },
  },
  {
    id: "access.no_login_access_support", domain: "Access Control", severity: "Low",
    title: "Users Cannot Grant Login Access To Support",
    description: "End users cannot grant their login access to support staff.",
    info: "User-initiated login grants create an unmonitored path for a third party to act with that user's full permissions.",
    remediation: "Setup > Login Access Policies: clear 'Administrators Can Log in as Any User' delegation for end users.",
    check: { source: "metadata", kind: "setting", path: "access.usersGrantLoginAccess", op: "==", value: false },
    compliance: { NIST_800_53: ["AC-6(9)"], ISO_27001_2022: ["A.8.2"] },
  },
  {
    id: "access.admin_login_as_any_user", domain: "Access Control", severity: "Low",
    title: "Restrict Admin Login As Any User",
    description: "The org-wide 'admins can log in as any user' option is off.",
    info: "Broad impersonation lets any administrator assume any identity, including highly privileged ones, with limited friction.",
    remediation: "Setup > Login Access Policies: disable 'Administrators Can Log in as Any User' and grant it case by case.",
    check: { source: "metadata", kind: "setting", path: "access.adminLoginAsAnyUser", op: "==", value: false },
    compliance: { NIST_800_53: ["AC-6(9)", "AC-6(10)"], SOC2: ["CC6.1"], ISO_27001_2022: ["A.8.2"] },
    tags: ["over-permissioning"],
  },
  {
    id: "access.first_party_cookies", domain: "Access Control", severity: "Low",
    title: "Require First-Party Use of Salesforce Cookies",
    description: "Hostnames compatible with third-party cookie blocking are in use.",
    info: "First-party cookie handling keeps session material out of third-party contexts that browsers increasingly restrict or leak.",
    remediation: "Setup > My Domain: enable third-party cookie blocking compatible hostnames.",
    check: { source: "metadata", kind: "setting", path: "access.firstPartyCookies", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.26"], NIST_800_53: ["SC-23"] },
  },
  {
    id: "access.stabilized_hostnames", domain: "Access Control", severity: "Low",
    title: "Stabilized My Domain Hostnames",
    description: "My Domain uses stabilized (instance-independent) hostnames.",
    info: "Stable hostnames keep allowlists, SSO endpoints and integrations valid across instance migrations instead of silently breaking.",
    remediation: "Setup > My Domain > Routing: enable stabilized hostnames.",
    check: { source: "metadata", kind: "setting", path: "access.stabilizedHostnames", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.20"], NIST_800_53: ["CM-6"] },
  },
  {
    id: "access.log_redirections", domain: "Access Control", severity: "Low",
    title: "Log Redirections Out of Salesforce",
    description: "Outbound redirections are logged for review.",
    info: "Redirect logs reveal phishing and open-redirect abuse that would otherwise leave no trace for investigators.",
    remediation: "Setup > My Domain > Routing: enable redirection logging.",
    check: { source: "metadata", kind: "setting", path: "access.logRedirections", op: "==", value: true },
    compliance: { NIST_800_53: ["AU-2", "AU-12"], SOC2: ["CC7.2"] },
  },

  // ───────────────────────────── Password Management ─────────────────────────────
  {
    id: "pwd.expiration_org", domain: "Password Management", severity: "High",
    title: "Password Expiration Policy (org)",
    description: "Org password expiration follows modern guidance (no forced periodic rotation).",
    info: "NIST SP 800-63B recommends against forced periodic password expiration; rotate only on evidence of compromise.",
    remediation: "Setup > Password Policies: set 'User passwords expire in' to 'Never expires' and rely on MFA + breach monitoring.",
    check: { source: "healthcheck", kind: "setting", path: "pwd.expirationDays", op: "==", value: 0 },
    compliance: { NIST_800_53: ["IA-5(1)"], ISO_27001_2022: ["A.8.5"] },
  },
  {
    id: "pwd.min_lifetime", domain: "Password Management", severity: "Medium",
    title: "Minimum One-Day Password Lifetime",
    description: "A minimum password lifetime is enforced.",
    info: "Prevents users from cycling through the password history to return to a favored password immediately.",
    remediation: "Setup > Password Policies: enforce a minimum 1-day password lifetime.",
    check: { source: "healthcheck", kind: "setting", path: "pwd.minLifetime", op: "==", value: true },
    compliance: { NIST_800_53: ["IA-5(1)"] },
  },
  {
    id: "pwd.min_length", domain: "Password Management", severity: "Medium",
    title: "Minimum Password Length ≥ 8",
    description: "Minimum password length is at least 8 characters.",
    info: "Longer minimums materially increase resistance to brute-force and guessing attacks.",
    remediation: "Setup > Password Policies: set minimum password length to 8 or greater.",
    check: { source: "healthcheck", kind: "setting", path: "pwd.minLength", op: ">=", value: 8 },
    compliance: { NIST_800_53: ["IA-5(1)"], PCI_DSS_4: ["8.3.6"] },
  },
  {
    id: "pwd.history", domain: "Password Management", severity: "Medium",
    title: "Enforce Password History",
    description: "Password history is enforced (≥ 1 remembered password).",
    info: "Prevents immediate reuse of a previous password on reset.",
    remediation: "Setup > Password Policies: set 'Enforce password history' to remember at least 1 password.",
    check: { source: "healthcheck", kind: "setting", path: "pwd.history", op: ">=", value: 1 },
    compliance: { NIST_800_53: ["IA-5(1)"] },
  },

  {
    id: "pwd.complexity", domain: "Password Management", severity: "Medium",
    title: "Password Complexity Requirement",
    description: "Passwords must mix character types (not 'No restriction').",
    info: "Complexity requirements raise the search space for brute-force and dictionary attacks against local credentials.",
    remediation: "Setup > Password Policies: set complexity to at least alphanumeric plus a special character.",
    check: { source: "metadata", kind: "setting", path: "pwd.complexity", op: "!=", value: "NoRestriction" },
    compliance: { NIST_800_53: ["IA-5(1)"], ISO_27001_2022: ["A.8.5"], PCI_DSS_4: ["8.3.6"] },
  },
  {
    id: "pwd.question_restriction", domain: "Password Management", severity: "Low",
    title: "Password Hint Cannot Contain the Password",
    description: "The password hint/answer cannot repeat the password itself.",
    info: "A hint that echoes the password hands the credential to anyone who can trigger the recovery prompt.",
    remediation: "Setup > Password Policies: set the password question requirement to exclude the password.",
    check: { source: "metadata", kind: "setting", path: "pwd.questionRestriction", op: "!=", value: "None" },
    compliance: { NIST_800_53: ["IA-5"], ISO_27001_2022: ["A.8.5"] },
  },
  {
    id: "pwd.obscure_secret_answer", domain: "Password Management", severity: "Low",
    title: "Obscure Secret Answer for Password Resets",
    description: "The security-question answer is masked as it is typed.",
    info: "Masking the recovery answer prevents shoulder-surfing of a value that can reset the account password.",
    remediation: "Setup > Password Policies: enable 'Obscure secret answer for password resets'.",
    check: { source: "metadata", kind: "setting", path: "pwd.obscureSecretAnswer", op: "==", value: true },
    compliance: { NIST_800_53: ["IA-5", "IA-6"], ISO_27001_2022: ["A.8.5"] },
  },

  // ───────────────────────────── Permissions ─────────────────────────────
  {
    id: "perm.view_all_data", domain: "Permissions", severity: "High",
    title: "Users with View All Data",
    description: "Number of active users with 'View All Data' is within policy.",
    info: "View All Data bypasses all sharing rules; it should be tightly limited to a small set of admins.",
    remediation: "Review View All Data holders and remove the permission where not business-critical.",
    check: { source: "soql", kind: "count", metric: "ViewAllData", op: "<=", threshold: 15 },
    compliance: { ISO_27001_2022: ["A.8.2", "A.8.3"], NIST_800_53: ["AC-6(7)"], SOC2: ["CC6.1"], PCI_DSS_4: ["7.2.4"] },
    tags: ["over-permissioning"],
  },
  {
    id: "perm.modify_all_data", domain: "Permissions", severity: "High",
    title: "Users with Modify All Data",
    description: "Number of active users with 'Modify All Data' is within policy.",
    info: "Modify All Data grants full create/edit/delete on all records regardless of sharing — the highest-impact data permission.",
    remediation: "Restrict Modify All Data to a minimal admin group; use targeted permission sets instead.",
    check: { source: "soql", kind: "count", metric: "ModifyAllData", op: "<=", threshold: 15 },
    compliance: { ISO_27001_2022: ["A.8.2", "A.8.3"], NIST_800_53: ["AC-6(7)"], SOC2: ["CC6.1"], PCI_DSS_4: ["7.2.4"] },
    tags: ["over-permissioning"],
  },
  {
    id: "perm.manage_users", domain: "Permissions", severity: "Medium",
    title: "Users with Manage Users",
    description: "Number of active users with 'Manage Users' is within policy.",
    info: "Manage Users can reset passwords, change profiles, and escalate privileges of other users.",
    remediation: "Limit Manage Users to identity/admin staff and review quarterly.",
    check: { source: "soql", kind: "count", metric: "ManageUsers", op: "<=", threshold: 17 },
    compliance: { NIST_800_53: ["AC-6(7)"], SOC2: ["CC6.1"] },
    tags: ["over-permissioning"],
  },
  {
    id: "perm.bulk_hard_delete", domain: "Permissions", severity: "Medium",
    title: "Users with Bulk API Hard Delete",
    description: "Number of active users with 'Bulk API Hard Delete' is within policy.",
    info: "Hard delete bypasses the Recycle Bin, permanently destroying records with no recovery.",
    remediation: "Remove Bulk API Hard Delete from all but a small set of controlled integration users.",
    check: { source: "soql", kind: "count", metric: "BulkApiHardDelete", op: "<=", threshold: 15 },
    compliance: { NIST_800_53: ["AC-6(7)"], ISO_27001_2022: ["A.8.3"] },
    tags: ["over-permissioning"],
  },
  {
    id: "perm.weekly_export", domain: "Permissions", severity: "Medium",
    title: "Users with Weekly Data Export",
    description: "Number of active users who can run the Weekly Data Export is within policy.",
    info: "Full data-export capability is a bulk-exfiltration risk if abused or compromised.",
    remediation: "Restrict 'Weekly Data Export' to backup/admin roles.",
    check: { source: "soql", kind: "count", metric: "WeeklyDataExport", op: "<=", threshold: 15 },
    compliance: { NIST_800_53: ["AC-6(7)"], ISO_27001_2022: ["A.8.12"] },
    tags: ["over-permissioning", "data-exfiltration"],
  },
  {
    id: "perm.delete_accounts", domain: "Permissions", severity: "Medium",
    title: "Users Who Can Delete Accounts",
    description: "Number of users with delete access on Account is within policy.",
    info: "Broad delete rights on core objects increase the blast radius of a compromised or careless user.",
    remediation: "Remove Account delete from profiles/permission sets that do not require it.",
    check: { source: "soql", kind: "count", metric: "DeleteAccounts", op: "<=", threshold: 5 },
    compliance: { NIST_800_53: ["AC-6(7)"], SOC2: ["CC6.1"] },
    tags: ["over-permissioning"],
  },

  // ───────────────────────────── MFA ─────────────────────────────
  {
    id: "mfa.all_direct_ui", domain: "MFA", severity: "Medium",
    title: "Require MFA for All Direct UI Logins",
    description: "MFA is required for all direct (non-SSO) UI logins.",
    info: "Direct UI logins without MFA are the most common account-takeover vector.",
    remediation: "Setup > Identity > MFA: require MFA for all direct UI logins (or enforce via permission set).",
    check: { source: "metadata", kind: "setting", path: "mfa.allDirectUiLogins", op: "==", value: true },
    compliance: { NIST_800_53: ["IA-2(1)"], PCI_DSS_4: ["8.4.2"], SOC2: ["CC6.1"] },
  },
  {
    id: "mfa.verify_registration", domain: "MFA", severity: "Medium",
    title: "Identity Verification During MFA Registration",
    description: "Identity is verified when users register MFA methods.",
    info: "Verifying identity at registration prevents an attacker binding their own MFA device to a victim account.",
    remediation: "Enable identity verification during MFA/device registration in Session Settings.",
    check: { source: "metadata", kind: "setting", path: "mfa.verifyOnRegistration", op: "==", value: true },
    compliance: { NIST_800_53: ["IA-2"], ISO_27001_2022: ["A.8.5"] },
  },

  {
    id: "mfa.sms_identity", domain: "MFA", severity: "Medium",
    title: "Identity Verification With SMS",
    description: "Users can verify identity by text message.",
    info: "SMS is a weaker second factor than an authenticator app, but enabling a verification path is far stronger than password-only login.",
    remediation: "Setup > Identity Verification: allow users to verify identity by SMS, and prefer app-based factors where possible.",
    check: { source: "metadata", kind: "setting", path: "mfa.smsIdentityVerification", op: "==", value: true },
    compliance: { NIST_800_53: ["IA-2(1)"], SOC2: ["CC6.1"], PCI_DSS_4: ["8.4.2"] },
  },
  {
    id: "mfa.security_key", domain: "MFA", severity: "Low",
    title: "Physical Security Key Authentication (U2F/WebAuthn)",
    description: "Hardware security keys are allowed as a verification method.",
    info: "Hardware keys are origin-bound, making them the only widely deployed factor that resists real-time phishing proxies.",
    remediation: "Setup > Identity Verification: allow security keys (U2F/WebAuthn) for identity verification.",
    check: { source: "metadata", kind: "setting", path: "mfa.securityKeyU2F", op: "==", value: true },
    compliance: { NIST_800_53: ["IA-2(1)", "IA-2(2)"], ISO_27001_2022: ["A.8.5"] },
  },
  {
    id: "mfa.built_in_authenticator", domain: "MFA", severity: "Low",
    title: "Built-In Authenticator (Face ID / Touch ID)",
    description: "Platform biometric authenticators are permitted.",
    info: "Built-in platform authenticators give users a low-friction strong factor, which raises real MFA adoption rates.",
    remediation: "Setup > Identity Verification: enable the built-in authenticator as a verification method.",
    check: { source: "metadata", kind: "setting", path: "mfa.builtInAuthenticator", op: "==", value: true },
    compliance: { NIST_800_53: ["IA-2(1)"], ISO_27001_2022: ["A.8.5"] },
  },
  {
    id: "mfa.lightning_login", domain: "MFA", severity: "Low",
    title: "Passwordless Login (Lightning Login)",
    description: "Passwordless authenticator-based login is enabled.",
    info: "Passwordless login removes the reusable shared secret entirely, eliminating credential-stuffing and password-reuse risk.",
    remediation: "Setup > Session Settings: enable Lightning Login and assign the required permission.",
    check: { source: "metadata", kind: "setting", path: "mfa.lightningLogin", op: "==", value: true },
    compliance: { NIST_800_53: ["IA-2(1)"], SOC2: ["CC6.1"] },
  },

  // ───────────────────────────── Data Leakage Protection ─────────────────────────────
  {
    id: "dlp.owd_public", domain: "Data Leakage Protection", severity: "High",
    title: "Objects With Default External Access = Public",
    description: "No object has an org-wide default external access of Public.",
    info: "Public external OWD exposes records to guest/community users regardless of intent.",
    remediation: "Setup > Sharing Settings: set external OWD to Private for the flagged objects and grant access explicitly.",
    check: { source: "metadata", kind: "listEmpty", list: "objectsPublicExternal" },
    compliance: { ISO_27001_2022: ["A.8.12"], NIST_800_53: ["AC-21"] },
    tags: ["data-exposure"],
  },
  {
    id: "dlp.dashboard_snapshots", domain: "Data Leakage Protection", severity: "High",
    title: "Dashboard Component Snapshots Disabled",
    description: "Posting dashboard component snapshots to feeds is disabled.",
    info: "Snapshots can surface data to users who lack access to the underlying report.",
    remediation: "Setup > Report and Dashboard Settings: disable dashboard component snapshots.",
    check: { source: "metadata", kind: "setting", path: "dlp.dashboardSnapshots", op: "==", value: false },
    compliance: { ISO_27001_2022: ["A.8.12"], NIST_800_53: ["AC-21"] },
    tags: ["data-exposure"],
  },
  {
    id: "dlp.public_links_nopwd", domain: "Data Leakage Protection", severity: "High",
    title: "Public Links / Content Deliveries Without Password",
    description: "No active public link or content delivery lacks password protection.",
    info: "Password-less public deliveries expose files to anyone with the URL.",
    remediation: "Add passwords/expirations to the flagged content deliveries, or revoke them.",
    check: { source: "soql", kind: "listEmpty", list: "publicLinksNoPassword" },
    compliance: { ISO_27001_2022: ["A.8.12"], NIST_800_53: ["AC-6(6)"] },
    tags: ["data-exposure"],
  },

  // ───────────────────────────── Secure Baseline ─────────────────────────────
  {
    id: "baseline.pim_enhanced", domain: "Secure Baseline", severity: "High",
    title: "Enhanced Personal Information Management",
    description: "Enhanced PIM restricts which personal fields are visible to other internal users.",
    info: "Without enhanced PIM, users can see colleagues' personal contact fields by default.",
    remediation: "Setup > User Management Settings: enable Enhanced Personal Information Management.",
    check: { source: "metadata", kind: "setting", path: "baseline.pimEnhanced", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.5.34"], NIST_CSF_2: ["PR.AA-01"] },
  },
  {
    id: "baseline.guest_api_enabled", domain: "Secure Baseline", severity: "High",
    title: "Guest Profile Does Not Have API Enabled",
    description: "No guest/site profile has 'API Enabled'.",
    info: "API access on a guest profile lets unauthenticated visitors query data programmatically.",
    remediation: "Remove 'API Enabled' from all guest/site profiles.",
    check: { source: "metadata", kind: "setting", path: "baseline.guestApiEnabled", op: "==", value: false },
    compliance: { NIST_800_53: ["AC-6(10)"], ISO_27001_2022: ["A.8.2"] },
    tags: ["guest"],
  },
  {
    id: "baseline.profile_filtering", domain: "Secure Baseline", severity: "High",
    title: "Profile Filtering for Guest Users",
    description: "Profile filtering hides internal user records from guest users.",
    info: "Without profile filtering, guest users may enumerate internal user records.",
    remediation: "Setup > User Management Settings: enable profile filtering for guest users.",
    check: { source: "metadata", kind: "setting", path: "baseline.profileFiltering", op: "==", value: true },
    compliance: { ISO_27001_2022: ["A.8.9", "A.5.34"] },
    tags: ["guest"],
  },

  {
    id: "baseline.post_for_sessions", domain: "Secure Baseline", severity: "Low",
    title: "Disallow POST Requests for Session Creation",
    description: "Sessions cannot be created from cross-domain POST requests.",
    info: "Allowing POST-created sessions widens the surface for session fixation, where an attacker plants a known session identifier.",
    remediation: "Setup > Session Settings: disable 'Allow POST requests for session creation'.",
    check: { source: "metadata", kind: "setting", path: "baseline.postForSessions", op: "==", value: false },
    compliance: { ISO_27001_2022: ["A.8.26"], NIST_800_53: ["SC-23"] },
  },
  {
    id: "baseline.cross_org_redirects", domain: "Secure Baseline", severity: "Low",
    title: "Block Cross-Org Redirects",
    description: "Redirects to other Salesforce orgs are not allowed.",
    info: "Cross-org redirects can be chained into convincing phishing flows that begin on a legitimate, trusted org hostname.",
    remediation: "Setup > Session Settings: disable cross-org redirects.",
    check: { source: "metadata", kind: "setting", path: "baseline.crossOrgRedirects", op: "==", value: false },
    compliance: { NIST_800_53: ["SC-7", "AC-4"], ISO_27001_2022: ["A.8.20"] },
  },
  {
    id: "baseline.redirect_block_mode", domain: "Secure Baseline", severity: "Low",
    title: "Block Unsafe External Redirects",
    description: "Redirect block mode is enforced for untrusted destinations.",
    info: "Block mode stops open-redirect abuse outright rather than merely warning the user, who will usually click through.",
    remediation: "Setup > Session Settings: enable redirect block mode for non-allowlisted URLs.",
    check: { source: "metadata", kind: "setting", path: "baseline.redirectBlockMode", op: "==", value: true },
    compliance: { NIST_800_53: ["SC-7", "AC-4"], ISO_27001_2022: ["A.8.20"] },
  },
  {
    id: "baseline.user_self_deactivate", domain: "Secure Baseline", severity: "Low",
    title: "Disable External User Self-Deactivation",
    description: "External users cannot deactivate their own accounts.",
    info: "Self-deactivation lets an account disappear mid-investigation, destroying the live context an incident responder needs.",
    remediation: "Setup > User Management Settings: disable user self-deactivation.",
    check: { source: "metadata", kind: "setting", path: "baseline.userSelfDeactivate", op: "==", value: false },
    compliance: { NIST_800_53: ["AC-2"], ISO_27001_2022: ["A.5.16"] },
  },
  {
    id: "baseline.restrict_email_domains", domain: "Secure Baseline", severity: "Low",
    title: "Email Domain Allowlist",
    description: "User email addresses are restricted to approved domains.",
    info: "An allowlist stops accounts being created or repointed to attacker-controlled mailboxes that can receive reset links.",
    remediation: "Setup > User Management Settings: enable the email domain allowlist and populate approved domains.",
    check: { source: "metadata", kind: "setting", path: "baseline.restrictEmailDomains", op: "==", value: true },
    compliance: { NIST_800_53: ["AC-2", "IA-5"], ISO_27001_2022: ["A.5.16"] },
  },

  // ───────────────────────────── Auditing ─────────────────────────────
  {
    id: "audit.event_log_generation", domain: "Auditing", severity: "High",
    title: "Event Log Generation Enabled",
    description: "Event monitoring / event log file generation is enabled.",
    info: "Event logs are the primary source for detecting anomalous access and building an audit trail.",
    remediation: "Enable Event Monitoring and event log file generation.",
    check: { source: "metadata", kind: "setting", path: "audit.eventLogGeneration", op: "==", value: true },
    compliance: { NIST_800_53: ["AU-2", "AU-12"], SOC2: ["CC7.2"] },
  },
  {
    id: "audit.event_log_delete", domain: "Auditing", severity: "High",
    title: "Deletion of Event Monitoring Records Disabled",
    description: "Deletion of event monitoring records is disabled.",
    info: "Allowing deletion of audit records undermines the integrity of the audit trail.",
    remediation: "Disable deletion of event monitoring / big object audit records.",
    check: { source: "metadata", kind: "setting", path: "audit.eventLogDeleteDisabled", op: "==", value: true },
    compliance: { NIST_800_53: ["AU-9"], SOC2: ["CC7.2"] },
  },

  {
    id: "audit.user_field_history", domain: "Auditing", severity: "Low",
    title: "User Field History Tracking",
    description: "Changes to user records are tracked in field history.",
    info: "User field history is what proves when a profile, email or permission changed, and by whom, during a privilege-escalation investigation.",
    remediation: "Setup > User Management Settings: enable user field history tracking.",
    check: { source: "metadata", kind: "setting", path: "audit.userFieldHistory", op: "==", value: true },
    compliance: { NIST_800_53: ["AU-2", "AU-12"], SOC2: ["CC7.2"], ISO_27001_2022: ["A.8.15"] },
  },

  // ───────────────────────────── Privacy Control ─────────────────────────────
  {
    id: "privacy.view_pii", domain: "Privacy Control", severity: "Medium",
    title: "Users With Permission to View PII",
    description: "Number of users granted 'View Encrypted/PII Data' is within policy.",
    info: "PII visibility should be minimized to reduce exposure and support data-minimization requirements.",
    remediation: "Restrict PII-view permissions to roles with a documented need.",
    check: { source: "soql", kind: "count", metric: "ViewPII", op: "<=", threshold: 0 },
    compliance: { ISO_27001_2022: ["A.5.34"], NIST_800_53: ["AC-6(7)"] },
    tags: ["privacy"],
  },

  // ──────────────────── Connected Apps & OAuth (Metadata API) ────────────────────
  // Every rule here reads the nested oauthConfig / oauthPolicy of each ConnectedApp.
  {
    id: "capp.oauth_full_scope", domain: "Connected Apps", severity: "High",
    title: "Connected Apps With Full Access OAuth Scope",
    description: "No connected app is granted the 'full' OAuth scope.",
    info: "The 'full' scope gives an integration everything its authorizing user can do, so a single leaked token becomes an org-wide compromise. Scope it down to the objects the integration actually touches.",
    remediation: "Setup > App Manager > edit the app > OAuth Scopes: replace 'Full access' with the narrowest scopes required.",
    check: { source: "metadata", kind: "listEmpty", list: "oauthFullScopeApps" },
    compliance: { ISO_27001_2022: ["A.5.15"], NIST_800_53: ["AC-6"], SOC2: ["CC6.3"] },
    tags: ["oauth", "third-party"],
  },
  {
    id: "capp.ip_relaxation", domain: "Connected Apps", severity: "High",
    title: "Connected App IP Restrictions Enforced",
    description: "No connected app relaxes IP restrictions.",
    info: "Relaxing IP restrictions lets a stolen token be replayed from anywhere in the world, defeating the org's trusted-IP perimeter.",
    remediation: "Setup > Connected Apps > Manage > edit policies: set IP Relaxation to 'Enforce IP restrictions'.",
    check: { source: "metadata", kind: "listEmpty", list: "connectedAppsIpRelax" },
    compliance: { ISO_27001_2022: ["A.8.20"], NIST_800_53: ["AC-17"] },
    tags: ["oauth", "third-party"],
  },
  {
    id: "capp.nonexpiring_refresh", domain: "Connected Apps", severity: "High",
    title: "Connected Apps With Non-Expiring Refresh Tokens",
    description: "No connected app uses a refresh token valid until revoked.",
    info: "An 'until revoked' refresh token is effectively a permanent credential; if it leaks, access persists indefinitely and silently.",
    remediation: "Set the refresh token policy to expire after a defined period or period of inactivity.",
    check: { source: "metadata", kind: "listEmpty", list: "connectedAppsNonExpiring" },
    compliance: { ISO_27001_2022: ["A.5.17"], NIST_800_53: ["AC-12"], SOC2: ["CC6.1"] },
    tags: ["oauth", "third-party"],
  },
  {
    id: "capp.pkce_required", domain: "Connected Apps", severity: "High",
    title: "OAuth PKCE Requirement",
    description: "Every connected app requires PKCE for the authorization-code flow.",
    info: "Without PKCE an intercepted authorization code can be redeemed by an attacker, which is the classic redirect-hijack path for public clients.",
    remediation: "Setup > App Manager > edit the app: enable 'Require Proof Key for Code Exchange (PKCE)'.",
    check: { source: "metadata", kind: "listEmpty", list: "connectedAppsNoPkce" },
    compliance: { ISO_27001_2022: ["A.8.5"], NIST_800_53: ["IA-2"], SOC2: ["CC6.1"] },
    tags: ["oauth"],
  },
  {
    id: "capp.client_credentials", domain: "Connected Apps", severity: "High",
    title: "OAuth Client Credentials Flow Restricted",
    description: "No connected app enables the client-credentials flow.",
    info: "Client credentials authenticate with no user context and no MFA, running as a fixed execution user, so the secret alone is enough to act on the org.",
    remediation: "Disable the client-credentials flow unless required; if required, bind it to a dedicated least-privilege integration user.",
    check: { source: "metadata", kind: "listEmpty", list: "connectedAppsClientCredentials" },
    compliance: { ISO_27001_2022: ["A.5.16"], NIST_800_53: ["AC-6", "IA-5"] },
    tags: ["oauth"],
  },
  {
    id: "capp.secret_required", domain: "Connected Apps", severity: "High",
    title: "Consumer Secret Required",
    description: "No connected app treats the consumer secret as optional.",
    info: "An app with an optional secret is a public client: anyone holding the consumer key can impersonate it and start an OAuth flow against the org.",
    remediation: "Setup > App Manager > edit the app: clear 'Consumer Secret is not required'.",
    check: { source: "metadata", kind: "listEmpty", list: "connectedAppsPublicClient" },
    compliance: { ISO_27001_2022: ["A.5.17"], NIST_800_53: ["IA-5"] },
    tags: ["oauth"],
  },
  {
    id: "capp.refresh_secret", domain: "Connected Apps", severity: "Medium",
    title: "Secret Required For Refresh Token Exchange",
    description: "Every connected app requires the client secret when exchanging a refresh token.",
    info: "If the secret is not required on refresh, a stolen refresh token is independently sufficient to mint new access tokens forever.",
    remediation: "Enable 'Require secret for refresh token flow' on the connected app.",
    check: { source: "metadata", kind: "listEmpty", list: "connectedAppsRefreshNoSecret" },
    compliance: { ISO_27001_2022: ["A.5.17"], NIST_800_53: ["IA-5"] },
    tags: ["oauth"],
  },
  {
    id: "capp.introspect_all", domain: "Connected Apps", severity: "Medium",
    title: "Token Introspection Limited To Own Tokens",
    description: "No connected app is allowed to introspect all tokens.",
    info: "'Introspect all tokens' lets one integration inspect tokens issued to other integrations, turning a single compromised app into an org-wide token oracle.",
    remediation: "Disable 'Introspect All Tokens' unless the app is a dedicated authorization server.",
    check: { source: "metadata", kind: "listEmpty", list: "connectedAppsIntrospectAll" },
    compliance: { ISO_27001_2022: ["A.5.15"], NIST_800_53: ["AC-6"] },
    tags: ["oauth"],
  },
  {
    id: "capp.restricted_audience", domain: "Connected Apps", severity: "Medium",
    title: "Connected Apps Limited To Specific Profiles Or Permission Sets",
    description: "Every connected app restricts access to named profiles or permission sets.",
    info: "An app with no profile or permission-set restriction is pre-authorized for the whole org, so any user can consent and expand its reach.",
    remediation: "Setup > Connected Apps > Manage: set 'Admin approved users are pre-authorized' and assign specific profiles or permission sets.",
    check: { source: "metadata", kind: "listEmpty", list: "connectedAppsUnrestricted" },
    compliance: { ISO_27001_2022: ["A.5.15"], NIST_800_53: ["AC-3"], SOC2: ["CC6.3"] },
    tags: ["oauth", "third-party"],
  },
  {
    id: "capp.single_logout", domain: "Connected Apps", severity: "Low",
    title: "Connected App Single Logout Configured",
    description: "Every connected app defines a single-logout endpoint.",
    info: "Without single logout, terminating a Salesforce session leaves the downstream app's session alive, so revoking access does not actually end it.",
    remediation: "Configure the Single Logout URL on the connected app.",
    check: { source: "metadata", kind: "listEmpty", list: "connectedAppsNoSingleLogout" },
    compliance: { ISO_27001_2022: ["A.8.5"], NIST_800_53: ["AC-12"] },
    tags: ["oauth"],
  },
  {
    id: "capp.https_callback", domain: "Connected Apps", severity: "High",
    title: "Connected App Callback URLs Use HTTPS",
    description: "No connected app uses a plaintext HTTP callback URL.",
    info: "An HTTP callback exposes the authorization code and token in transit to anyone on the network path.",
    remediation: "Change the callback URL to HTTPS on the flagged connected apps.",
    check: { source: "metadata", kind: "listEmpty", list: "connectedAppsInsecureCallback" },
    compliance: { ISO_27001_2022: ["A.8.24"], NIST_800_53: ["SC-8"] },
    tags: ["oauth", "encryption-in-transit"],
  },

  // ─────────────────── External Client Apps (Metadata API) ───────────────────
  // ExtlClntApp* is the Connected App successor and a separate metadata family:
  // none of the capp.* rules above see these apps. Credential handling comes from
  // ExtlClntAppGlobalOauthSettings, runtime policy from ExtlClntAppOauthConfigurablePolicies.
  {
    id: "eca.pkce_required", domain: "External Client Apps", severity: "High",
    title: "External Client App PKCE Requirement",
    description: "Every external client app requires PKCE.",
    info: "Without PKCE an intercepted authorization code can be redeemed by an attacker. External client apps default to requiring it, so an app with it off was deliberately weakened.",
    remediation: "Setup > External Client App Manager > edit the app's OAuth settings: enable 'Require Proof Key for Code Exchange (PKCE)'.",
    check: { source: "metadata", kind: "listEmpty", list: "ecaNoPkce" },
    compliance: { ISO_27001_2022: ["A.8.5"], NIST_800_53: ["IA-2"], SOC2: ["CC6.1"] },
    tags: ["oauth"],
  },
  {
    id: "eca.refresh_rotation", domain: "External Client Apps", severity: "Medium",
    title: "External Client App Refresh Token Rotation",
    description: "Every external client app rotates refresh tokens on use.",
    info: "Rotation invalidates the previous refresh token each time one is redeemed, so a stolen token stops working as soon as the legitimate client refreshes.",
    remediation: "Enable refresh token rotation on the app's OAuth settings.",
    check: { source: "metadata", kind: "listEmpty", list: "ecaNoRefreshRotation" },
    compliance: { ISO_27001_2022: ["A.5.17"], NIST_800_53: ["IA-5"] },
    tags: ["oauth"],
  },
  {
    id: "eca.refresh_secret", domain: "External Client Apps", severity: "Medium",
    title: "External Client App Secret Required For Refresh Token",
    description: "Every external client app requires its client secret when refreshing.",
    info: "If the secret is not required on refresh, a stolen refresh token alone can mint new access tokens indefinitely.",
    remediation: "Enable 'Require secret for refresh token flow' on the app's OAuth settings.",
    check: { source: "metadata", kind: "listEmpty", list: "ecaRefreshNoSecret" },
    compliance: { ISO_27001_2022: ["A.5.17"], NIST_800_53: ["IA-5"] },
    tags: ["oauth"],
  },
  {
    id: "eca.consumer_secret_required", domain: "External Client Apps", severity: "High",
    title: "External Client App Consumer Secret Required",
    description: "No external client app treats its consumer secret as optional.",
    info: "An app with an optional secret is a public client: the consumer key alone is enough to begin an OAuth flow against the org.",
    remediation: "Clear 'Consumer secret is not required' on the app's OAuth settings.",
    check: { source: "metadata", kind: "listEmpty", list: "ecaPublicClient" },
    compliance: { ISO_27001_2022: ["A.5.17"], NIST_800_53: ["IA-5"] },
    tags: ["oauth"],
  },
  {
    id: "eca.introspect_all", domain: "External Client Apps", severity: "Medium",
    title: "External Client App Token Introspection Limited",
    description: "No external client app can introspect all tokens.",
    info: "Introspecting all tokens lets one app inspect credentials issued to others, turning a single compromise into an org-wide token oracle.",
    remediation: "Disable 'Introspect All Tokens' unless the app is a dedicated authorization server.",
    check: { source: "metadata", kind: "listEmpty", list: "ecaIntrospectAll" },
    compliance: { ISO_27001_2022: ["A.5.15"], NIST_800_53: ["AC-6"] },
    tags: ["oauth"],
  },
  {
    id: "eca.https_callback", domain: "External Client Apps", severity: "High",
    title: "External Client App Callback URLs Use HTTPS",
    description: "No external client app uses a plaintext HTTP callback URL.",
    info: "An HTTP callback exposes the authorization code to anyone on the network path.",
    remediation: "Change the callback URL to HTTPS on the flagged apps.",
    check: { source: "metadata", kind: "listEmpty", list: "ecaInsecureCallback" },
    compliance: { ISO_27001_2022: ["A.8.24"], NIST_800_53: ["SC-8"] },
    tags: ["oauth", "encryption-in-transit"],
  },
  {
    id: "eca.ip_relaxation", domain: "External Client Apps", severity: "High",
    title: "External Client App IP Restrictions Enforced",
    description: "No external client app relaxes IP restrictions.",
    info: "Relaxing IP restrictions lets a stolen token be replayed from anywhere, defeating the org's trusted-IP perimeter.",
    remediation: "Set the app's IP relaxation policy to 'Enforce IP restrictions'.",
    check: { source: "metadata", kind: "listEmpty", list: "ecaIpRelax" },
    compliance: { ISO_27001_2022: ["A.8.20"], NIST_800_53: ["AC-17"] },
    tags: ["oauth"],
  },
  {
    id: "eca.client_credentials", domain: "External Client Apps", severity: "High",
    title: "External Client App Client Credentials Flow Restricted",
    description: "No external client app enables the client-credentials flow.",
    info: "Client credentials authenticate with no user context and no MFA, running as a fixed execution user, so the secret alone is enough to act on the org.",
    remediation: "Disable the client-credentials flow, or bind it to a dedicated least-privilege integration user.",
    check: { source: "metadata", kind: "listEmpty", list: "ecaClientCredentials" },
    compliance: { ISO_27001_2022: ["A.5.16"], NIST_800_53: ["AC-6", "IA-5"] },
    tags: ["oauth"],
  },
  {
    id: "eca.token_exchange", domain: "External Client Apps", severity: "Medium",
    title: "External Client App Token Exchange Flow Restricted",
    description: "No external client app enables the token-exchange flow.",
    info: "Token exchange lets an app trade one token for another, which can be used to widen scope or impersonate a subject if the app is compromised.",
    remediation: "Disable the token-exchange flow unless the app federates identity by design.",
    check: { source: "metadata", kind: "listEmpty", list: "ecaTokenExchange" },
    compliance: { ISO_27001_2022: ["A.5.15"], NIST_800_53: ["AC-6"] },
    tags: ["oauth"],
  },
  {
    id: "eca.permitted_users", domain: "External Client Apps", severity: "Medium",
    title: "External Client App Permitted Users Are Admin-Approved",
    description: "No external client app allows all self-authorized users.",
    info: "'All self-authorized' means any user can consent and connect the app themselves, so its reach grows without an admin ever reviewing it.",
    remediation: "Set the permitted users policy to 'Admin approved users are pre-authorized' and assign specific profiles or permission sets.",
    check: { source: "metadata", kind: "listEmpty", list: "ecaSelfAuthorized" },
    compliance: { ISO_27001_2022: ["A.5.15"], NIST_800_53: ["AC-3"], SOC2: ["CC6.3"] },
    tags: ["oauth", "third-party"],
  },
  {
    id: "eca.refresh_policy", domain: "External Client Apps", severity: "High",
    title: "External Client Apps Without Non-Expiring Refresh Tokens",
    description: "No external client app uses an infinite refresh token policy.",
    info: "An infinite refresh token is a permanent credential; if it leaks, access persists indefinitely and silently.",
    remediation: "Set the refresh token policy to expire after a defined lifetime or period of inactivity.",
    check: { source: "metadata", kind: "listEmpty", list: "ecaNonExpiringRefresh" },
    compliance: { ISO_27001_2022: ["A.5.17"], NIST_800_53: ["AC-12"], SOC2: ["CC6.1"] },
    tags: ["oauth"],
  },
  {
    id: "eca.refresh_validity", domain: "External Client Apps", severity: "Low",
    title: "External Client App Refresh Token Validity Within One Year",
    description: "No external client app has a refresh token valid for more than 365 days.",
    info: "A multi-year refresh token is effectively permanent in practice; the credential outlives the integration and often the person who created it.",
    remediation: "Reduce the refresh token validity period to a year or less.",
    check: { source: "metadata", kind: "listEmpty", list: "ecaLongRefreshValidity" },
    compliance: { ISO_27001_2022: ["A.5.17"], NIST_800_53: ["AC-12"] },
    tags: ["oauth"],
  },
  {
    id: "eca.session_level", domain: "External Client Apps", severity: "Low",
    title: "External Client App Requires High Assurance Session",
    description: "Every external client app requires a high-assurance session level.",
    info: "A standard session level lets the app be used from a session that never passed identity verification, so MFA can be bypassed in practice.",
    remediation: "Set the app's required session level to High Assurance.",
    check: { source: "metadata", kind: "listEmpty", list: "ecaStandardSessionLevel" },
    compliance: { ISO_27001_2022: ["A.8.5"], NIST_800_53: ["IA-2(1)"] },
    tags: ["oauth"],
  },

  // ──────────────────────────── Key Management ────────────────────────────
  // Backed by the Certificate metadata type (expiry, key size, signer, exportability).
  {
    id: "key.no_expired_certs", domain: "Key Management", severity: "High",
    title: "No Expired Certificates",
    description: "No certificate in the org has passed its expiration date.",
    info: "An expired certificate breaks the integrations that depend on it and pressures teams into insecure workarounds such as disabling validation.",
    remediation: "Setup > Certificate and Key Management: regenerate or remove the expired certificates.",
    check: { source: "metadata", kind: "listEmpty", list: "certsExpired" },
    compliance: { ISO_27001_2022: ["A.8.24"], NIST_800_53: ["SC-12"], SOC2: ["CC6.1"] },
    tags: ["encryption-in-transit"],
  },
  {
    id: "key.certs_expiring_soon", domain: "Key Management", severity: "Medium",
    title: "No Certificates Expiring Within 90 Days",
    description: "No certificate expires in the next 90 days.",
    info: "Ninety days is the practical lead time to rotate a certificate and coordinate every consumer of it before an outage forces a rushed change.",
    remediation: "Plan rotation for the flagged certificates and update the integrations that reference them.",
    check: { source: "metadata", kind: "listEmpty", list: "certsExpiringSoon" },
    compliance: { ISO_27001_2022: ["A.8.24"], NIST_800_53: ["SC-12"] },
    tags: ["encryption-in-transit"],
  },
  {
    id: "key.min_key_size", domain: "Key Management", severity: "High",
    title: "Certificate Key Length At Least 2048 Bits",
    description: "No certificate uses a key shorter than 2048 bits.",
    info: "RSA keys below 2048 bits are below current guidance and are rejected by an increasing number of counterparties.",
    remediation: "Regenerate the flagged certificates with a 2048-bit or larger key.",
    check: { source: "metadata", kind: "listEmpty", list: "certsWeakKey" },
    compliance: { ISO_27001_2022: ["A.8.24"], NIST_800_53: ["SC-12", "SC-13"], PCI_DSS_4: ["4.2.1"] },
    tags: ["encryption-in-transit"],
  },
  {
    id: "key.ca_signed", domain: "Key Management", severity: "Medium",
    title: "Certificates Are CA-Signed",
    description: "Every certificate used by the org is signed by a certificate authority.",
    info: "Self-signed certificates carry no external trust chain, so counterparties cannot distinguish a legitimate rotation from an attacker substituting their own certificate.",
    remediation: "Replace self-signed certificates with CA-signed certificates for anything used externally.",
    check: { source: "metadata", kind: "listEmpty", list: "certsSelfSigned" },
    compliance: { ISO_27001_2022: ["A.8.24"], NIST_800_53: ["SC-12"] },
    tags: ["encryption-in-transit"],
  },
  {
    id: "key.private_key_not_exportable", domain: "Key Management", severity: "High",
    title: "Certificate Private Keys Not Exportable",
    description: "No certificate allows its private key to be exported.",
    info: "An exportable private key can be copied out of the org by any admin, after which every signature and TLS session it protects can be forged offline.",
    remediation: "Recreate the flagged certificates without the exportable-private-key option.",
    check: { source: "metadata", kind: "listEmpty", list: "certsExportableKey" },
    compliance: { ISO_27001_2022: ["A.8.24"], NIST_800_53: ["SC-12"], SOC2: ["CC6.1"] },
    tags: ["encryption-in-transit"],
  },
];
